# Generated by Django 4.2.2 on 2024-02-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('shipping_date', models.DateField()),
                ('ship_mode', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('region', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=30)),
                ('sub_category', models.CharField(max_length=20)),
                ('sales', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('profit', models.FloatField()),
                ('order_rating', models.IntegerField()),
            ],
        ),
    ]
